Ext.define('MyApp.store.Personnel', {
    extend: 'Ext.data.Store',

    alias: 'store.personnel',

    fields: [
        'name', 'email', 'phone'
    ],

    data: { items: [
        {
            "Id": 1,
            "Title": "X-Men",
            "Distributed-by": "20th Century Fox",
            "Tomatometer": "81",
            "Budget": 75,
            "Box-office": 296.3,
            "Box-office-Budget-ratio": 395.07,
            "Premiere-Date": "07/13/00",
            "Running-time": 104,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 2,
            "Title": "Spider-Man",
            "Distributed-by": "Columbia Pictures",
            "Tomatometer": "89",
            "Budget": 139,
            "Box-office": 821.7,
            "Box-office-Budget-ratio": 591.15,
            "Premiere-Date": "04/30/02",
            "Running-time": 121,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 3,
            "Title": "Daredevil",
            "Distributed-by": "20th Century Fox",
            "Tomatometer": "44",
            "Budget": 78,
            "Box-office": 179.2,
            "Box-office-Budget-ratio": 229.74,
            "Premiere-Date": "02/14/03",
            "Running-time": 103,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 4,
            "Title": "X2",
            "Distributed-by": "20th Century Fox",
            "Tomatometer": "86",
            "Budget": 110,
            "Box-office": 407.7,
            "Box-office-Budget-ratio": 370.64,
            "Premiere-Date": "04/24/03",
            "Running-time": 133,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 5,
            "Title": "Hulk",
            "Distributed-by": "Universal Pictures",
            "Tomatometer": "61",
            "Budget": 137,
            "Box-office": 245.4,
            "Box-office-Budget-ratio": 179.12,
            "Premiere-Date": "06/20/03",
            "Running-time": 138,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 6,
            "Title": "The Punisher",
            "Distributed-by": "Columbia Pictures",
            "Tomatometer": "29",
            "Budget": 33,
            "Box-office": 54.7,
            "Box-office-Budget-ratio": 165.76,
            "Premiere-Date": "03/30/04",
            "Running-time": 123,
            "MPAA": "R",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 7,
            "Title": "Spider-Man 2",
            "Distributed-by": "Columbia Pictures",
            "Tomatometer": "93",
            "Budget": 200,
            "Box-office": 783.8,
            "Box-office-Budget-ratio": 391.90,
            "Premiere-Date": "04/16/04",
            "Running-time": 127,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 8,
            "Title": "Catwoman",
            "Distributed-by": "Warner Bros. Pictures",
            "Tomatometer": "9",
            "Budget": 100,
            "Box-office": 82.1,
            "Box-office-Budget-ratio": 82.10,
            "Premiere-Date": "06/25/04",
            "Running-time": 104,
            "MPAA": "PG-13",
            "Editorial": "DC Comics"
        },
        {
            "Id": 9,
            "Title": "Hellboy",
            "Distributed-by": "Columbia Pictures",
            "Tomatometer": "81",
            "Budget": 66,
            "Box-office": 99.3,
            "Box-office-Budget-ratio": 150.45,
            "Premiere-Date": "07/19/04",
            "Running-time": 122,
            "MPAA": "PG-13",
            "Editorial": "Dark Horse Comics"
        },
        {
            "Id": 10,
            "Title": "Sky High",
            "Distributed-by": "Buena Vista Pictures",
            "Tomatometer": "73",
            "Budget": 35,
            "Box-office": 86.4,
            "Box-office-Budget-ratio": 246.86,
            "Premiere-Date": "01/14/05",
            "Running-time": 100,
            "MPAA": "PG",
            "Editorial": "Not Available"
        },
        {
            "Id": 11,
            "Title": "Elektra",
            "Distributed-by": "20th Century Fox",
            "Tomatometer": "10",
            "Budget": 43,
            "Box-office": 56.7,
            "Box-office-Budget-ratio": 131.86,
            "Premiere-Date": "05/31/05",
            "Running-time": 97,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 12,
            "Title": "Batman Begins",
            "Distributed-by": "Warner Bros. Pictures",
            "Tomatometer": "84",
            "Budget": 150,
            "Box-office": 374.2,
            "Box-office-Budget-ratio": 249.47,
            "Premiere-Date": "06/29/05",
            "Running-time": 140,
            "MPAA": "PG-13",
            "Editorial": "DC Comics"
        },
        {
            "Id": 13,
            "Title": "Fantastic Four",
            "Distributed-by": "20th Century Fox",
            "Tomatometer": "27",
            "Budget": 100,
            "Box-office": 330.6,
            "Box-office-Budget-ratio": 330.60,
            "Premiere-Date": "07/08/05",
            "Running-time": 106,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 14,
            "Title": "X-Men: The Last Stand",
            "Distributed-by": "20th Century Fox",
            "Tomatometer": "58",
            "Budget": 210,
            "Box-office": 459.4,
            "Box-office-Budget-ratio": 218.76,
            "Premiere-Date": "05/25/06",
            "Running-time": 104,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 15,
            "Title": "Superman Returns",
            "Distributed-by": "Warner Bros. Pictures",
            "Tomatometer": "76",
            "Budget": 204,
            "Box-office": 391.1,
            "Box-office-Budget-ratio": 191.72,
            "Premiere-Date": "06/21/06",
            "Running-time": 154,
            "MPAA": "PG-13",
            "Editorial": "DC Comics"
        },
        {
            "Id": 16,
            "Title": "Ghost Rider",
            "Distributed-by": "Columbia Pictures",
            "Tomatometer": "26",
            "Budget": 110,
            "Box-office": 228.7,
            "Box-office-Budget-ratio": 207.91,
            "Premiere-Date": "01/15/07",
            "Running-time": 110,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 17,
            "Title": "Spider-Man 3",
            "Distributed-by": "Columbia Pictures",
            "Tomatometer": "63",
            "Budget": 258,
            "Box-office": 890.9,
            "Box-office-Budget-ratio": 345.31,
            "Premiere-Date": "04/16/07",
            "Running-time": 139,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 18,
            "Title": "Fantastic Four: Rise of the Silver Surfer",
            "Distributed-by": "20th Century Fox",
            "Tomatometer": "37",
            "Budget": 130,
            "Box-office": 289,
            "Box-office-Budget-ratio": 222.31,
            "Premiere-Date": "06/12/07",
            "Running-time": 92,
            "MPAA": "PG",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 19,
            "Title": "Iron Man",
            "Distributed-by": "Paramount Pictures",
            "Tomatometer": "94",
            "Budget": 140,
            "Box-office": 585.2,
            "Box-office-Budget-ratio": 418.00,
            "Premiere-Date": "04/14/08",
            "Running-time": 126,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 20,
            "Title": "The Incredible Hulk",
            "Distributed-by": "Universal Pictures",
            "Tomatometer": "67",
            "Budget": 150,
            "Box-office": 263.4,
            "Box-office-Budget-ratio": 175.60,
            "Premiere-Date": "06/08/08",
            "Running-time": 112,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 21,
            "Title": "The Dark Knight",
            "Distributed-by": "Warner Bros. Pictures",
            "Tomatometer": "94",
            "Budget": 185,
            "Box-office": 1005,
            "Box-office-Budget-ratio": 543.24,
            "Premiere-Date": "06/16/08",
            "Running-time": 152,
            "MPAA": "PG-13",
            "Editorial": "DC Comics"
        },
        {
            "Id": 22,
            "Title": "Hancock",
            "Distributed-by": "Columbia Pictures",
            "Tomatometer": "41",
            "Budget": 150,
            "Box-office": 624.3,
            "Box-office-Budget-ratio": 416.20,
            "Premiere-Date": "07/11/08",
            "Running-time": 92,
            "MPAA": "PG-13",
            "Editorial": "Not Available"
        },
        {
            "Id": 23,
            "Title": "Hellboy II: The Golden Army",
            "Distributed-by": "Universal Pictures",
            "Tomatometer": "85",
            "Budget": 85,
            "Box-office": 160.4,
            "Box-office-Budget-ratio": 188.71,
            "Premiere-Date": "07/14/08",
            "Running-time": 120,
            "MPAA": "PG-13",
            "Editorial": "Dark Horse Comics"
        },
        {
            "Id": 24,
            "Title": "Punisher: War Zone",
            "Distributed-by": "Lionsgate",
            "Tomatometer": "27",
            "Budget": 35,
            "Box-office": 10.1,
            "Box-office-Budget-ratio": 28.86,
            "Premiere-Date": "12/05/08",
            "Running-time": 103,
            "MPAA": "R",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 25,
            "Title": "The Spirit",
            "Distributed-by": "Lionsgate",
            "Tomatometer": "14",
            "Budget": 60,
            "Box-office": 39,
            "Box-office-Budget-ratio": 65.00,
            "Premiere-Date": "12/25/08",
            "Running-time": 103,
            "MPAA": "PG-13",
            "Editorial": "Quality Comics"
        },
        {
            "Id": 26,
            "Title": "Watchmen",
            "Distributed-by": "Warner Bros. Pictures",
            "Tomatometer": "65",
            "Budget": 130,
            "Box-office": 185.3,
            "Box-office-Budget-ratio": 142.54,
            "Premiere-Date": "02/23/09",
            "Running-time": 163,
            "MPAA": "R",
            "Editorial": "DC Comics"
        },
        {
            "Id": 27,
            "Title": "X-Men Origins: Wolverine",
            "Distributed-by": "20th Century Fox",
            "Tomatometer": "38",
            "Budget": 150,
            "Box-office": 373.1,
            "Box-office-Budget-ratio": 248.73,
            "Premiere-Date": "04/09/09",
            "Running-time": 107,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 28,
            "Title": "Kick-Ass",
            "Distributed-by": "Universal Pictures",
            "Tomatometer": "76",
            "Budget": 28,
            "Box-office": 96.2,
            "Box-office-Budget-ratio": 343.57,
            "Premiere-Date": "03/26/10",
            "Running-time": 117,
            "MPAA": "R",
            "Editorial": "Icon Comics"
        },
        {
            "Id": 29,
            "Title": "Iron Man 2",
            "Distributed-by": "Paramount Pictures",
            "Tomatometer": "72",
            "Budget": 200,
            "Box-office": 623.9,
            "Box-office-Budget-ratio": 311.95,
            "Premiere-Date": "04/26/10",
            "Running-time": 125,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 30,
            "Title": "The Green Hornet",
            "Distributed-by": "Columbia Pictures",
            "Tomatometer": "43",
            "Budget": 120,
            "Box-office": 227.8,
            "Box-office-Budget-ratio": 189.83,
            "Premiere-Date": "01/10/11",
            "Running-time": 119,
            "MPAA": "PG-13",
            "Editorial": "Dynamite Comics"
        },
        {
            "Id": 31,
            "Title": "Thor",
            "Distributed-by": "Paramount Pictures",
            "Tomatometer": "77",
            "Budget": 150,
            "Box-office": 449.3,
            "Box-office-Budget-ratio": 299.53,
            "Premiere-Date": "04/17/11",
            "Running-time": 114,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 32,
            "Title": "X-Men: First Class",
            "Distributed-by": "20th Century Fox",
            "Tomatometer": "86",
            "Budget": 140,
            "Box-office": 353.6,
            "Box-office-Budget-ratio": 252.57,
            "Premiere-Date": "05/25/11",
            "Running-time": 132,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 33,
            "Title": "Green Lantern",
            "Distributed-by": "Warner Bros. Pictures",
            "Tomatometer": "26",
            "Budget": 200,
            "Box-office": 219.8,
            "Box-office-Budget-ratio": 109.90,
            "Premiere-Date": "06/17/11",
            "Running-time": 114,
            "MPAA": "PG-13",
            "Editorial": "DC Comics"
        },
        {
            "Id": 34,
            "Title": "Captain America: The first Avenger",
            "Distributed-by": "Paramount Pictures",
            "Tomatometer": "80",
            "Budget": 140,
            "Box-office": 370.6,
            "Box-office-Budget-ratio": 264.71,
            "Premiere-Date": "07/19/11",
            "Running-time": 124,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 35,
            "Title": "Chronicle",
            "Distributed-by": "20th Century Fox",
            "Tomatometer": "85",
            "Budget": 12,
            "Box-office": 126.6,
            "Box-office-Budget-ratio": 1055.00,
            "Premiere-Date": "01/28/12",
            "Running-time": 84,
            "MPAA": "PG-13",
            "Editorial": "Not Available"
        },
        {
            "Id": 36,
            "Title": "Ghost Rider: Spirit of Vengeance",
            "Distributed-by": "Columbia Pictures",
            "Tomatometer": "17",
            "Budget": 57,
            "Box-office": 132.6,
            "Box-office-Budget-ratio": 232.63,
            "Premiere-Date": "02/17/12",
            "Running-time": 95,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 37,
            "Title": "The Amazing Spider-Man",
            "Distributed-by": "Columbia Pictures",
            "Tomatometer": "73",
            "Budget": 230,
            "Box-office": 757.9,
            "Box-office-Budget-ratio": 329.52,
            "Premiere-Date": "04/11/12",
            "Running-time": 136,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 38,
            "Title": "The Dark Knight Rises",
            "Distributed-by": "Warner Bros. Pictures",
            "Tomatometer": "87",
            "Budget": 230,
            "Box-office": 1085,
            "Box-office-Budget-ratio": 471.74,
            "Premiere-Date": "06/30/12",
            "Running-time": 165,
            "MPAA": "PG-13",
            "Editorial": "DC Comics"
        },
        {
            "Id": 39,
            "Title": "Dredd",
            "Distributed-by": "Lionsgate",
            "Tomatometer": "78",
            "Budget": 30,
            "Box-office": 41.5,
            "Box-office-Budget-ratio": 138.33,
            "Premiere-Date": "07/11/12",
            "Running-time": 95,
            "MPAA": "R",
            "Editorial": "2000 AD"
        },
        {
            "Id": 40,
            "Title": "Marvel's The Avengers",
            "Distributed-by": "Walt Disney Studios",
            "Tomatometer": "92",
            "Budget": 220,
            "Box-office": 1520,
            "Box-office-Budget-ratio": 690.91,
            "Premiere-Date": "07/16/12",
            "Running-time": 143,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 41,
            "Title": "Iron Man 3",
            "Distributed-by": "Walt Disney Studios",
            "Tomatometer": "79",
            "Budget": 200,
            "Box-office": 1215,
            "Box-office-Budget-ratio": 607.50,
            "Premiere-Date": "04/14/13",
            "Running-time": 130,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 42,
            "Title": "Man of Steel",
            "Distributed-by": "Warner Bros. Pictures",
            "Tomatometer": "55",
            "Budget": 225,
            "Box-office": 668,
            "Box-office-Budget-ratio": 296.89,
            "Premiere-Date": "06/10/13",
            "Running-time": 143,
            "MPAA": "PG-13",
            "Editorial": "DC Comics"
        },
        {
            "Id": 43,
            "Title": "The Wolverine",
            "Distributed-by": "20th Century Fox",
            "Tomatometer": "69",
            "Budget": 120,
            "Box-office": 414.8,
            "Box-office-Budget-ratio": 345.67,
            "Premiere-Date": "07/16/13",
            "Running-time": 126,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 44,
            "Title": "Kick-Ass 2",
            "Distributed-by": "Universal Pictures",
            "Tomatometer": "31",
            "Budget": 28,
            "Box-office": 60.7,
            "Box-office-Budget-ratio": 216.79,
            "Premiere-Date": "08/14/13",
            "Running-time": 103,
            "MPAA": "R",
            "Editorial": "Icon Comics"
        },
        {
            "Id": 45,
            "Title": "Thor: The Dark World",
            "Distributed-by": "Walt Disney Studios",
            "Tomatometer": "66",
            "Budget": 170,
            "Box-office": 644.6,
            "Box-office-Budget-ratio": 379.18,
            "Premiere-Date": "10/22/13",
            "Running-time": 112,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 46,
            "Title": "Captain America: The Winter Soldier",
            "Distributed-by": "Walt Disney Studios",
            "Tomatometer": "89",
            "Budget": 170,
            "Box-office": 714.4,
            "Box-office-Budget-ratio": 420.24,
            "Premiere-Date": "03/13/14",
            "Running-time": 136,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 47,
            "Title": "The Amazing Spider-Man 2",
            "Distributed-by": "Columbia Pictures",
            "Tomatometer": "52",
            "Budget": 200,
            "Box-office": 709,
            "Box-office-Budget-ratio": 354.50,
            "Premiere-Date": "03/31/14",
            "Running-time": 142,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 48,
            "Title": "Teenage Mutant Ninja Turtles: Out of the Shadows",
            "Distributed-by": "Paramount Pictures",
            "Tomatometer": "22",
            "Budget": 125,
            "Box-office": 493.3,
            "Box-office-Budget-ratio": 394.64,
            "Premiere-Date": "05/10/14",
            "Running-time": 101,
            "MPAA": "PG-13",
            "Editorial": "Mirage Studios"
        },
        {
            "Id": 49,
            "Title": "X-Men Days of Future Past",
            "Distributed-by": "20th Century Fox",
            "Tomatometer": "91",
            "Budget": 200,
            "Box-office": 747.9,
            "Box-office-Budget-ratio": 373.95,
            "Premiere-Date": "07/21/14",
            "Running-time": 131,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 50,
            "Title": "Guardians of the Galaxy",
            "Distributed-by": "Walt Disney Studios",
            "Tomatometer": "91",
            "Budget": 195.9,
            "Box-office": 773.3,
            "Box-office-Budget-ratio": 394.74,
            "Premiere-Date": "07/29/14",
            "Running-time": 122,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 51,
            "Title": "Big Hero 6",
            "Distributed-by": "Walt Disney Studios",
            "Tomatometer": "89",
            "Budget": 165,
            "Box-office": 657.8,
            "Box-office-Budget-ratio": 398.67,
            "Premiere-Date": "10/23/14",
            "Running-time": 102,
            "MPAA": "PG",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 52,
            "Title": "Avengers: Age of Ultron",
            "Distributed-by": "Walt Disney Studios",
            "Tomatometer": "75",
            "Budget": 267.4,
            "Box-office": 1405,
            "Box-office-Budget-ratio": 525.43,
            "Premiere-Date": "04/13/15",
            "Running-time": 142,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 53,
            "Title": "Ant-Man",
            "Distributed-by": "Walt Disney Studios",
            "Tomatometer": "81",
            "Budget": 130,
            "Box-office": 519.4,
            "Box-office-Budget-ratio": 399.54,
            "Premiere-Date": "06/29/15",
            "Running-time": 117,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 54,
            "Title": "Fantastic Four",
            "Distributed-by": "20th Century Fox",
            "Tomatometer": "9",
            "Budget": 120,
            "Box-office": 168,
            "Box-office-Budget-ratio": 140.00,
            "Premiere-Date": "08/04/15",
            "Running-time": 100,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 55,
            "Title": "Deadpool",
            "Distributed-by": "20th Century Fox",
            "Tomatometer": "84",
            "Budget": 58,
            "Box-office": 782.6,
            "Box-office-Budget-ratio": 1349.31,
            "Premiere-Date": "02/08/16",
            "Running-time": 108,
            "MPAA": "R",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 56,
            "Title": "Batman v. Superman: Dawn of Justice",
            "Distributed-by": "Warner Bros. Pictures",
            "Tomatometer": "27",
            "Budget": 250,
            "Box-office": 872.7,
            "Box-office-Budget-ratio": 349.08,
            "Premiere-Date": "03/19/16",
            "Running-time": 151,
            "MPAA": "PG-13",
            "Editorial": "DC Comics"
        },
        {
            "Id": 57,
            "Title": "Captain America: Civil War",
            "Distributed-by": "Walt Disney Studios",
            "Tomatometer": "90",
            "Budget": 250,
            "Box-office": 1152,
            "Box-office-Budget-ratio": 460.80,
            "Premiere-Date": "04/12/16",
            "Running-time": 147,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 58,
            "Title": "Teenage Mutant Ninja Turtles: Out of the Shadows",
            "Distributed-by": "Paramount Pictures",
            "Tomatometer": "38",
            "Budget": 135,
            "Box-office": 239.3,
            "Box-office-Budget-ratio": 177.26,
            "Premiere-Date": "05/09/16",
            "Running-time": 112,
            "MPAA": "PG-13",
            "Editorial": "Mirage Studios"
        },
        {
            "Id": 59,
            "Title": "X-Men: Apocalypse",
            "Distributed-by": "20th Century Fox",
            "Tomatometer": "48",
            "Budget": 178,
            "Box-office": 542.7,
            "Box-office-Budget-ratio": 304.89,
            "Premiere-Date": "05/22/16",
            "Running-time": 144,
            "MPAA": "PG-13",
            "Editorial": "Marvel Comics"
        },
        {
            "Id": 60,
            "Title": "Suicide Squad",
            "Distributed-by": "Warner Bros. Pictures",
            "Tomatometer": "28",
            "Budget": 175,
            "Box-office": 575.4,
            "Box-office-Budget-ratio": 328.80,
            "Premiere-Date": "08/01/16",
            "Running-time": 123,
            "MPAA": "PG-13",
            "Editorial": "DC Comics"
        }
    ]},

    proxy: {
        type: 'memory',
        reader: {
            type: 'json',
            rootProperty: 'items'
        }
    }
});